# Introduction to NumPy

<small> Numpy because you deal with a lot of datasets in ml, to save time it's probably best to use the numerical python (Numpy) to do heavy computation as it is written in C under the hood </small>

In [ ]:
import numpy as np

Numpy Array

In [ ]:
array = np.array([1, 2, 3, 4, 5])
print("Numpy Array:", array)

In [ ]:
array * 2

Multimentional Arrays

In [ ]:
mda = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Numpy Array:\n", mda)
print("Shape of 2D Array:", mda.shape)

Chain Indexing

In [ ]:
print("Element at (1,2):", mda[1, 2])  
# Accessing element at row 1, column 2

#hain indexing
rows = np.array([0, 2])
cols = np.array([1, 2])

# can do md addition too
print(mda[0,0] + mda[2,2])  # Output: 10


slicing

In [ ]:
num_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

#array[start;end;step]

sliced_array = num_array[0:3, 1:4]
print("Sliced Array:\n", sliced_array)

#skip columns by only taking every second column
skipped_columns = num_array[:, ::2]

Apply functions using Vectoral Arithmetic

In [ ]:
array = np.array([1, 2, 3, 4, 5])

print("Original Array:", array)

print("Squared Array:", array ** 2)  # Element-wise squaring

print("Mean of Array:", np.mean(array))  # Mean of the array
print("Standard Deviation of Array:", np.std(array))  # Standard deviation
print("Sum of Array Elements:", np.sum(array))  # Sum of all elements
print("Maximum Element in Array:", np.max(array))  # Maximum element
print("Minimum Element in Array:", np.min(array))  # Minimum element
print("Array after adding 5:", array + 5)  # Adding 5 to each element
print("Array after multiplying by 3:", array * 3)  # Multiplying each
print("Square Root of Array Elements:", np.sqrt(array))  # Square root of each element
print("Round Numbers in Array:", np.round(np.array([1.2, 2.5, 3.7, 4.4, 5.9])))  # Rounding each element
#ceiling
print("Ceiling of Array Elements:", np.ceil(np.array([1.2, 2.5, 3.7, 4.4, 5.9])))  # Ceiling of each element
#floor
print("Floor of Array Elements:", np.floor(np.array([1.2, 2.5, 3.7, 4.4, 5.9])))  # Floor of each element

#return pi
print("Value of Pi:", np.pi)  # Value of pi



Element wise arithmetic

In [ ]:
array = np.array([1, 2, 3, 4, 5])
array2 = np.array([10, 20, 30, 40, 50])

print(array + array2)  # Element-wise addition
print(array - array2)  # Element-wise subtraction
print(array * array2)  # Element-wise multiplication
print(array / array2)  # Element-wise division
print(array ** 2 + array2 ** 2)  # Element-wise power and addition

Comparison Operators

In [ ]:
scores = np.array([85, 90, 78, 92, 88])

print(scores == 90)  # Check which scores are equal to 90
print(scores > 80)   # Check which scores are greater than 80

In [ ]:
scores[scores < 80] = 0
print(scores)

Aggregate functions

<small>typicall summarizes data and reurns a single value </small>

In [ ]:
array = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

#mean
print("Mean of each column:", np.mean(array, axis=0))  # Mean of each column
print("Mean of each row:", np.mean(array, axis=1))     # Mean of each row
#sum
print("Sum of each column:", np.sum(array, axis=0))    # Sum of
print("Sum of each row:", np.sum(array, axis=1))       # Sum of each row
#max
print("Max of each column:", np.max(array, axis=0))     # Max of
print("Max of each row:", np.max(array, axis=1))        # Max of each row
#var
print("Variance of each column:", np.var(array, axis=0))  # Variance of each column
print("Variance of each row:", np.var(array, axis=1))     # Variance
#std
print("Standard Deviation of each column:", np.std(array, axis=0))  #
print("Standard Deviation of each row:", np.std(array, axis=1))     #
#position of min value
print("Index of min in each column:", np.argmin(array, axis=0))  #
print("Index of min in each row:", np.argmin(array, axis=1))     #
#position of max value
print("Index of max in each column:", np.argmax(array, axis=0))  #
print("Index of max in each row:", np.argmax(array, axis=1))     # axis mean to apply to all rows or colums, remove if single data

Filtering

In [20]:
ages = np.array([[21,17,29], [20,16,18], [22,19,20], [60, 90, 81]])  

teenagers = ages[ages < 20]
print("Teenagers:\n", teenagers)    # note this makes a 1D array
print("Adults:\n", ages[(ages >= 20) & (ages < 60)])
print("Seniors:\n", ages[ages >= 60])


Teenagers:
 [17 16 18 19]
Adults:
 [21 29 20 22 20]
Seniors:
 [60 90 81]


In [ ]:
#using random
np.random.seed(0)  # For reproducibility
random_array = np.random.rand(3, 4)  # 3x4 array
random_sample = np.random.choice(random_array.flatten(), size=5, replace=False)
normal_dist_sample = np.random.normal(loc=50, scale=5, size=5)

Filtering but preserving original shape

In [ ]:
# condition, ndarrry, fill value
adults = np.where(ages >= 20, ages, np.nan)
adults
#only use if shape is important

array([[21., nan, 29.],
       [20., nan, nan],
       [22., nan, 20.],
       [60., 90., 81.]])

Assigned values to filtered elements

In [ ]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5, 6])

# Filter: values greater than 3
mask = arr > 3
print(mask)   # [False False False  True  True  True]

# Assign new value to filtered elements
arr[mask] = 99
print(arr)    # [ 1  2  3 99 99 99 ]
